vtruefile	/data1/swq/structure_tensor/2d_raw_ol.dat
vobsfile	/data1/swq/structure_tensor/2d_raw_ol.dat
multiplefile	/data1/swq/structure_tensor/2d_multiple_ol.dat
vinvfile	/data1/swq/structure_tensor/2d_ol.inv.dat
vresfile	/data1/swq/structure_tensor/2d_ol.res.dat
faifile	/data1/swq/structure_tensor/test1_2d_ol_multiple_orientation_w3_3p.dat
evofile	/data1/swq/structure_tensor/2d_evo_ol.dat
evosubfile	/data1/swq/structure_tensor/2d_sub_evo_ol.dat
nx	50
nz	200
dx	1.0
dz	1.0
nitermax	2000
lambda	0.1
niu	9E-5
epsmin	9E-28
type    l1
step    1E-3
